export const HELP_TEXT = [
  "Keys",
  "  ↑/k, ↓/j   move",
  "  Enter        go down; on a live attempt, focus its pane",
  "  Esc, ⌫      go up",
  "  r            redraw now",
  "  q            quit",
  "  ?            toggle this help",
  "",
  "Verbs",
  "  a  approve the graph        (plans, graph under cursor)",
  "  s  sweep                    (plans)",
  "  R  run the node             (graph, node under cursor)",
  "  J  judge the node           (graph, node under cursor)",
  "  c  cancel the node          (graph, node under cursor)",
  "  x  reset the node           (graph, node under cursor)",
  "  b  backfill the graph       (graph)",
  "  w  waive the gate           (node, gate under cursor)",
].join("\n");
