import type { Artifact } from "./artifacts.ts";
import type { Example } from "./corpus.ts";
import { diffVersions } from "./diff.ts";
import { codeFence } from "./fence.ts";
import { fieldTablesFor, type FieldRow } from "./fields.ts";
import type { SchemaFiles } from "./schemaFiles.ts";
import { firstSentence } from "./vocabulary.ts";

function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function renderFieldTable(rows: readonly FieldRow[]): string {
  const header =
    "| field | type | required | description |\n| --- | --- | --- | --- |";
  if (rows.length === 0) return `${header}\n| _(no fields)_ | | | |`;
  const body = rows
    .map(
      (row) =>
        `| \`${escapeCell(row.name)}\` | ${escapeCell(row.type)} | ${row.required ? "yes" : "no"} | ${escapeCell(row.description)} |`,
    )
    .join("\n");
  return `${header}\n${body}`;
}

function renderFieldsSection(artifact: Artifact, files: SchemaFiles): string {
  const current = artifact.versions.at(-1);
  if (current === undefined) return "";
  const tables = fieldTablesFor(current.schema, files, current.filePath);
  const [only] = tables;
  if (tables.length === 1 && only !== undefined)
    return renderFieldTable(only.rows);
  return tables
    .map(
      (table) =>
        `**kind: \`${table.heading ?? "?"}\`**\n\n${renderFieldTable(table.rows)}`,
    )
    .join("\n\n");
}

function renderVersionsSection(artifact: Artifact): string {
  return artifact.versions
    .map((version, index) => {
      const previous = index === 0 ? undefined : artifact.versions[index - 1];
      if (previous === undefined)
        return `- \`${version.tag}\`: the first version.`;
      return `- \`${version.tag}\`: ${diffVersions(previous, version).join("; ")}.`;
    })
    .join("\n");
}

function renderExample(
  tag: string,
  examples: ReadonlyMap<string, Example>,
): string {
  const example = examples.get(tag);
  if (example === undefined)
    return `_No example of \`${tag}\` was found in the corpus._`;
  const fence = codeFence(example.content);
  return `Source: \`${example.sourcePath}\`\n\n${fence}${example.language}\n${example.content}\n${fence}`;
}

function renderExamplesSection(
  artifact: Artifact,
  examples: ReadonlyMap<string, Example>,
): string {
  return artifact.versions
    .map(
      (version) =>
        `#### \`${version.tag}\`\n\n${renderExample(version.tag, examples)}`,
    )
    .join("\n\n");
}

function renderPurpose(
  term: string,
  vocabulary: ReadonlyMap<string, string>,
): string {
  const meaning = vocabulary.get(term);
  return meaning === undefined
    ? `No vocabulary entry for \`${term}\`.`
    : firstSentence(meaning);
}

function renderArtifact(
  artifact: Artifact,
  files: SchemaFiles,
  vocabulary: ReadonlyMap<string, string>,
  examples: ReadonlyMap<string, Example>,
): string {
  const currentTag = artifact.versions.at(-1)?.tag ?? artifact.term;
  return [
    `## ${artifact.term}`,
    "",
    renderPurpose(artifact.term, vocabulary),
    "",
    "### Versions",
    "",
    renderVersionsSection(artifact),
    "",
    `### Fields (\`${currentTag}\`)`,
    "",
    renderFieldsSection(artifact, files),
    "",
    "### Examples",
    "",
    renderExamplesSection(artifact, examples),
  ].join("\n");
}

export function renderReference(
  artifacts: readonly Artifact[],
  files: SchemaFiles,
  vocabulary: ReadonlyMap<string, string>,
  examples: ReadonlyMap<string, Example>,
): string {
  const sections = artifacts.map((artifact) =>
    renderArtifact(artifact, files, vocabulary, examples),
  );
  return [
    "# Shapes reference",
    "",
    "Generated by `interlock schema reference`; edits made directly to this file are overwritten. Regenerate with `pnpm interlock schema reference` after changing a schema under `schemas/`.",
    "",
    sections.join("\n\n"),
    "",
  ].join("\n");
}
